version: '3'

services:
  main:
    build: ./
    environment:
      PYTHONPATH: "./"
      SECRET_KEY: CHANGE-IT-PLEASE-THIS-IS-SUPER-SECRET
    volumes:
      - ./example:/var/www
      - ./stackstore:/var/www/stackstore
      - ./entrypoint.sh:/tmp/entrypoint.sh
    entrypoint:
      - /tmp/entrypoint.sh
    ports:
      - 8000:8000
